### ISSUE TITLE
Showing the percentage of every color is wanted please.

### ISSUE THREAD

**Issue by erinsnow** [tangdiforx/iOSPalette#3]
Hope to **get the percentage of every color** which has been extracted from the original case if possible. Otherwise **an estimated scale** would be OK as well if it's hard to be accurate.

The rates of all kinds of colors are great parameters for people to build a memory of a picture. Sometimes we use the Color-Card to match colors with wrong rates, and a less nice UI comes out than the original one. Human's visual system is so complicated that it's valuable to think much of the color's rate, I suppose.

Thank you for your awesome project.

是否能直接体现解析出来的**每种色调的百分比**？感谢。
如果不难处理的话，希望可以表明百分比；如果难以精确，给个**估值范围**也可以。

对于画面给人的总体印象，每种色调的占比是很重要的。比如我们看到色卡搭配很好看，但是用在自己的UI上可能就不那么靓丽，原因就是比例运用不当，体现不出原case的感觉。人的视觉系统蛮复杂的，比例应该是个重要的参数我想。

非常棒的 project，🙏&👍

**Comment by tangdiforx** [comment]
Thanks a lot for your great advice! I will  complete the task as soon as possible.Then I will add it to the "Change Log" as a new feature.I will remind you thourgh sina weibo and you can see it from the README.

谢谢你这么棒的建议，我会尽快完成这个需求。等我做完会去微博上提醒你哒，你可以在README的Change Log中看到~

**Comment by tangdiforx** [comment]
Done~
